stages:
  - build
  - deploy

variables:
  VPS_HOST: "$VPS_HOST"
  VPS_IP: "$VPS_IP"
  DOCKER_IMAGE_NAME: ward-backend-image
  CONTAINER_NAME: ward-backend-container

build_image:
  stage: build
  tags:
    - gc
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keygen -R $VPS_IP || true
    - ssh-keyscan $VPS_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - docker container stop $CONTAINER_NAME || true
    - docker container rm $CONTAINER_NAME || true
    - docker image rm $DOCKER_IMAGE_NAME || true
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker save -o nestjs-app.tar $DOCKER_IMAGE_NAME
  artifacts:
    paths:
      - nestjs-app.tar

deploy:
  stage: deploy
  tags:
    - gc
  before_script:
    - sudo apt-get update
    - sudo apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keygen -R $VPS_IP || true
    - ssh-keyscan $VPS_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $VPS_HOST "whoami"
    - ssh -i ~/.ssh/id_rsa admin11@$VPS_IP "mkdir -p /ward/app && echo 'Directory created.'"
    - scp -i ~/.ssh/id_rsa nestjs-app.tar admin11@$VPS_IP:/ward/app
    - echo "Deploying container on VPS"
    - ssh -i ~/.ssh/id_rsa admin11@$VPS_IP " whoami \ docker container stop $CONTAINER_NAME || true && \
                                       docker container rm $CONTAINER_NAME || true && \
                                       docker image rm $DOCKER_IMAGE_NAME || true && \
                                       docker load -i /ward/app/nestjs-app.tar && \
                                       docker run -d --name $CONTAINER_NAME -p 3000:3000 $DOCKER_IMAGE_NAME"
