stages:
  - build
  - deploy

variables:
  VPS_HOST: "$VPS_HOST"
  VPS_IP: "$VPS_IP"
  DOCKER_IMAGE_NAME: ward-backend-image
  CONTAINER_NAME: ward-backend-container

build_image:
  stage: build
  tags:
    - gc
    
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo $SSH_PRIVATE_KEY
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - >-
        ssh-keygen -R $VPS_HOST &&
        ssh-keyscan $VPS_HOST >> ~/.ssh/known_hosts &&
        chmod 644 ~/.ssh/known_hosts
  script:
    # Remove any existing container and image
    - docker container stop $CONTAINER_NAME || true
    - docker container rm $CONTAINER_NAME || true
    - docker image rm $DOCKER_IMAGE_NAME || true
    # Build the new image
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker save -o nestjs-app.tar $DOCKER_IMAGE_NAME
  artifacts:
    paths:
      - nestjs-app.tar

deploy:
  stage: deploy
  tags:
    - gc
  before_script:
    - sudo apt-get update
    - sudo apt-get install -y openssh-client
  script:
    # Ensure the destination directory exists
    - echo "Current user: $(whoami)"
    - ssh $VPS_HOST "whoami"
    - ssh $VPS_HOST "mkdir -p /ward/app"
    # Copy the image to the VPS
    - echo "Copying file to VPS"
    - sudo scp -i ~/.ssh/id_rsa ~/test/testing admin11@$VPS_IP:/ward/app
    # SSH into the VPS and deploy the container
    - echo "Deploying container on VPS"
    - ssh $VPS_HOST "
        docker container stop $CONTAINER_NAME || true &&
        docker container rm $CONTAINER_NAME || true &&
        docker image rm $DOCKER_IMAGE_NAME || true &&
        docker load -i /ward/app/nestjs-app.tar &&
        docker-compose -f /ward/app/docker-compose.yml up -d
      "
