version: "3.9"

services:
  nestjs-app:
    profiles:
      - dev
    container_name: nestjs-app
    image: registry.gitlab.com/dci-project/arqsoft-dci/proyectos/1s2024/ward/ward-app/ward-backend/ward-api/app:latest
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: bac
      POSTGRES_PASSWORD: ZtE%&S01h8
      POSTGRES_DB: ward
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: 
