version: "3.9"

networks:
  app_network:

services:
  nestjs-app:
    container_name: nestjs-app
    image: registry.gitlab.com/dci-project/arqsoft-dci/proyectos/1s2024/ward/ward-app/ward-backend/ward-api/app:latest
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
